"""initial tables

Revision ID: 9b73eb87610c
Revises: 
Create Date: 2026-06-18 20:10:51.972999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b73eb87610c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drafts', sa.Column('edited_reply', sa.Text(), nullable=True))
    op.add_column('drafts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'drafts', 'emails', ['email_id'], ['id'])
    op.add_column('emails', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('emails', sa.Column('category', sa.String(), nullable=True))
    op.add_column('emails', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('emails', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'emails', ['gmail_message_id'])
    op.create_foreign_key(None, 'emails', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'created_at')
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_constraint(None, 'emails', type_='unique')
    op.drop_column('emails', 'created_at')
    op.drop_column('emails', 'priority')
    op.drop_column('emails', 'category')
    op.drop_column('emails', 'user_id')
    op.drop_constraint(None, 'drafts', type_='foreignkey')
    op.drop_column('drafts', 'created_at')
    op.drop_column('drafts', 'edited_reply')
    # ### end Alembic commands ###
